"""add ats_checks table

Revision ID: ff36c43c3408
Revises: 67c46fb0f2ab
Create Date: 2025-11-10 12:58:35.539025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff36c43c3408'
down_revision: Union[str, Sequence[str], None] = '67c46fb0f2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ats_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('ats_score', sa.Integer(), nullable=False),
    sa.Column('issues_found', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('is_ats_friendly', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ats_checks_id'), 'ats_checks', ['id'], unique=False)
    op.create_index(op.f('ix_ats_checks_resume_id'), 'ats_checks', ['resume_id'], unique=False)
    op.create_index(op.f('ix_ats_checks_user_id'), 'ats_checks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ats_checks_user_id'), table_name='ats_checks')
    op.drop_index(op.f('ix_ats_checks_resume_id'), table_name='ats_checks')
    op.drop_index(op.f('ix_ats_checks_id'), table_name='ats_checks')
    op.drop_table('ats_checks')
    # ### end Alembic commands ###
